<?php

/**
 * Aria S.p.A.
 * OPEN 2.0
 *
 *
 * @package    amos\sitemanagement\views\site-management-element
 * @category   CategoryName
 */

use amos\sitemanagement\Module;
use amos\sitemanagement\assets\ModuleSiteManagementAsset;
use open20\amos\core\forms\ActiveForm;
use open20\amos\core\forms\CloseSaveButtonWidget;
use open20\amos\core\forms\Tabs;
use kartik\select2\Select2;

ModuleSiteManagementAsset::register($this);
$module = \Yii::$app->getModule(Module::getModuleName());
$enableFixedContainers = $module->enableFixedContainers;
/**
 * @var yii\web\View $this
 * @var amos\sitemanagement\models\SiteManagementElement $model
 * @var yii\widgets\ActiveForm $form
 * @var $dynamicModel \yii\base\DynamicModel
 */

$js = <<<JS
    function loadTemplate(id){
         $.ajax({
                   url: '/sitemanagement/site-management-template/is-template-model-content',
                   type: 'get',
                   data: {
                            'id' :id
                         },
                   success: function (data) {
                      var isModelContent = data['isModelContent'];
                      if(isModelContent == '1'){
                          $('#element-values').hide();
                      }
                      else {
                          $('#element-values').show();
                      }
                       $('#preview-template').html(data['html'])
                   }
              });
    }
    
    // load the preview on page load  if you do the rapid creation from the container
     if($('#template-id').length > 0 && $('#template-id').val().length > 0){
        loadTemplate( $('#template-id').val());
    }

    var selected_radio =$('input[type=radio]:checked');
    $(selected_radio)
    .parents('tr')
    .addClass('success');
    $('#template-id').on('select2:select', function(){
        loadTemplate($(this).val())
    });
JS;

$this->registerJs($js);
?>

<div class="site-management-element-form col-xs-12 nop">
    <?php $form = ActiveForm::begin([
        'options' => ['enctype' => 'multipart/form-data'] // important
    ]); ?>
    <?php $this->beginBlock('generale'); ?>

    <div class="row">
        <div class="col-md-8 col-xs-12">
            <?php if ($model->isNewRecord) {
                $query = amos\sitemanagement\models\SiteManagementTemplate::find();
                if($enableFixedContainers){
                    if(!empty($_GET['idContainer'])){
                        $container = \amos\sitemanagement\models\SiteManagementContainer::findOne($_GET['idContainer']);
                        if($container) {
                            $model->template_id =  $container->fixed_template_id;
                            $query->andWhere(['id' => $container->fixed_template_id]);
                        }
                    }
                }
                // generated by schmunk42\giiant\generators\crud\providers\core\RelationProvider::activeField
                echo $form->field($model, 'template_id')->widget(Select2::className(), [
                        'options' => [
                            'id' => 'template-id',
                            'placeholder' => Module::t('amossitemanagement', 'Select...')
                        ],
                        'data' => yii\helpers\ArrayHelper::map($query->all(), 'id', 'name'),
                    ]
                );
            } else {
                echo $form->field($model, 'template_id')->hiddenInput()->label(false);
                echo "<strong>" . Module::t('amossitemanagement', 'Template') . ": </strong>" . $model->siteManagementTemplate->name;
            } ?>
            <?= $form->field($model, 'title')->textInput(['maxlength' => true]) ?>
            <?= $form->field($model, 'description')->textarea(); ?>
        </div>
        <div class="col-md-4 col-xs-12">
            <div class="col-xs-12 nop sitemanagement-template-preview" id="preview-template">
                <?php if (!$model->isNewRecord) {
                    echo \amos\sitemanagement\widgets\SMContainerWidget::renderTemplatePreview($model->template_id);
                } ?>
            </div>
        </div>
        <div class="col-xs-12" id="element-values">
            <?php if(!$model->isNewRecord && count($dynamicModel->attributes()) > 0){ ?>
                <h3><?= Module::t('amossitemanagement', 'Element values'); ?></h3>
            <?php  } ?>
        </div>
    </div>

    <?php
    if (!$model->isNewRecord) { ?>
        <?php if (!empty($model->siteManagementTemplate->content_model)) {
            $contentModelId = $model->content_model_id;
            $classContentModel = $model->siteManagementTemplate->content_model;
            $classContentModelSearch = str_replace('models', 'models\search', $classContentModel) . 'Search';
            $contentModelSearch = new $classContentModelSearch();
            $modelContent = new $classContentModel();

            echo $this->render('_search_model_content', ['contentModelSearch' => $contentModelSearch, 'form' => $form]); ?>
            <?php \yii\widgets\Pjax::begin(['id' => 'container-pjax', 'timeout' => 20000, 'clientOptions' => ['data-pjax-container' => 'list-selected']]); ?>

            <?php if (!($contentModelSearch instanceof \open20\amos\core\record\ContentModel)) {
                throw new Exception('You need a more recent version of ' . $classContentModel);
            }
            $contentModelSearch->load(\Yii::$app->request->get());

            $dataProvider = $contentModelSearch->searchAll(\Yii::$app->request->get());
            if (!empty($contentModelId)) {
                $dataProvider->query->orderBy(new \yii\db\Expression($modelContent->tableName() . '.id=' . $contentModelId . ' desc, id desc'));
            }


            $columns = $contentModelSearch->getGridViewColumns();
            $columns[] = [
                'class' => \kartik\grid\RadioColumn::className(),
                'name' => 'SiteManagementElement[content_model_id]',
                'rowHighlight' => true,
                'radioOptions' => function ($model) use ($contentModelId) {
                    return [
                        'value' => $model->id,
                        'checked' => $model->id == $contentModelId,
                    ];
                }
            ];
            ?>

            <div class="col-lg-12 col-sm-12">
                <?php
                echo \open20\amos\core\views\AmosGridView::widget([
                    'id' => 'list-selected',
                    'dataProvider' => $dataProvider,
                    'columns' => $columns
                ]);
                ?>
            </div>
            <?php \yii\widgets\Pjax::end(); ?>
        <?php } else {
            foreach ($dynamicModel->attributes() as $attribute) { ?>
                <?php if (!empty($attributesTypes[$attribute])) { ?>
                    <?php if ($attributesTypes[$attribute] == 'text') { ?>
                        <div class="col-lg-12 col-sm-12">
                            <?= $form->field($dynamicModel, $attribute)->textarea(['rows' => 6]) ?>
                        </div>
                    <?php } else if ($attributesTypes[$attribute] == 'file') { ?>
                        <div class="col-lg-6 col-sm-6">
                            <div class="hidden">
                                <?= $form->field($dynamicModel, $attribute)->hiddenInput(['value' => 'image'])->label(false) ?>
                            </div>
                            <?php
                            echo $form->field($modelFieldImages, 'attachFiles')->widget(\open20\amos\attachments\components\AttachmentsInput::classname(), [
                                'id' => 'file-input-' . $attribute, // Optional
                                'model' => $modelFieldImages,
                                'options' => [ // Options of the Kartik's FileInput widget
                                    'multiple' => false, // If you want to allow multiple upload, default to false
                                ],
                                'pluginOptions' => [ // Plugin options of the Kartik's FileInput widget
                                    'maxFileCount' => 10, // Client max files
                                    'allowedPreviewTypes' => ['image'],
                                    'showPreview' => true,
                                ]
                            ])->label('Image') ?>
                        </div>
                    <?php } else if ($attributesTypes[$attribute] == 'html') { ?>
                        <div class="col-lg-12 col-sm-12">
                            <?= $form->field($dynamicModel, $attribute)->widget(\open20\amos\core\forms\TextEditorWidget::className(), [
                                'clientOptions' => [
                                    'lang' => substr(Yii::$app->language, 0, 2)
                                ]
                            ]) ?>
                        </div>
                    <?php } else { ?>
                        <div class="col-lg-6 col-sm-6">
                            <?= $form->field($dynamicModel, $attribute)->textInput(['maxlength' => true]) ?>
                        </div>
                    <?php }
                } ?>


            <?php } ?>
        <?php }
    } else { ?>
        <div class="col-xs-12 nop">
            <?= Module::t('amossitemanagement', '#is_needed_saving_the_element'); ?>
        </div>
    <?php } ?>
    <div class="clearfix"></div>
    <?php $this->endBlock(); ?>

    <?php $itemsTab[] = [
        'label' => Module::t('amossitemanagement', 'generale'),
        'content' => $this->blocks['generale'],
    ];
    ?>

    <?= Tabs::widget(
        [
            'encodeLabels' => false,
            'items' => $itemsTab
        ]
    );
    ?>
    <?= CloseSaveButtonWidget::widget([
        'model' => $model,
        'urlClose' => ((\Yii::$app->request->referrer && strpos(\Yii::$app->request->referrer, 'create') === false) ? \Yii::$app->request->referrer : \yii\helpers\Url::previous()),
    ]); ?>
    <?php ActiveForm::end(); ?>
</div>
