<?php

use open20\amos\core\helpers\Html;
use open20\amos\core\forms\ActiveForm;
use kartik\datecontrol\DateControl;
use open20\amos\core\forms\Tabs;
use open20\amos\core\forms\CloseSaveButtonWidget;
use yii\helpers\Url;
use kartik\select2\Select2;
use yii\helpers\ArrayHelper;
use amos\sitemanagement\Module;

/**
 * @var yii\web\View $this
 * @var amos\sitemanagement\models\SiteManagementLandingPubblication $model
 * @var yii\widgets\ActiveForm $form
 */


?>

<div class="site-management-landing-pubblication-form col-xs-12 nop">

    <?php $form = ActiveForm::begin(); ?>




    <?php $this->beginBlock('general'); ?>

    <div class="col-lg-6 col-sm-6">

        <?php echo
        $form->field($model, 'url')->widget(Select2::classname(), [
            'data' => $routes,
            'options' => ['placeholder' => Module::t('amossitemanagement', 'Select...')],
            'pluginOptions' => [
                'allowClear' => true
            ],
        ]);
        ?>
    </div>
    <div class="col-lg-6 col-sm-6">
        <?= // generated by schmunk42\giiant\generators\crud\providers\core\RelationProvider::activeField
        $form->field($model, 'landing_id')->widget( Select2::className(), [
            'data' => yii\helpers\ArrayHelper::map(amos\sitemanagement\models\SiteManagementLanding::find()->all(), 'id', 'name'),
                'options' => ['placeholder' => Module::t('amossitemanagement', 'Select...')]
          ]
        ); ?>
    </div>

    <div class="col-xs-12">
        <h4><?= Module::t('amossitemanagement', 'Pubblication date') ?></h4>
    </div>
    <div class="col-lg-6 col-sm-6">
        <?= $form->field($model, 'start_date')->widget(DateControl::className(), [
            'type' => DateControl::FORMAT_DATETIME,
        ]) ?>
    </div>

    <div class="col-lg-6 col-sm-6">
        <?= $form->field($model, 'end_date')->widget(DateControl::className(), [
            'type' => DateControl::FORMAT_DATETIME,
        ]) ?>
    </div>

    <div class="col-xs-12">
        <h4><?= Module::t('amossitemanagement', 'Daily intervall of pubblication') ?></h4>
    </div>
    <div class="col-xs-6">
        <?php
        $model->start_time = empty($model->start_time) ? date('00:00:00') : $model->start_time;
        ?>
        <?php echo  $form->field($model, 'start_time')->widget(DateControl::className(), [
            'type' => DateControl::FORMAT_TIME,
        ]) ?>
    </div>
    <div class="col-xs-6">
        <?php
        $model->end_time = empty($model->end_time) ? date('23:59:00') : $model->end_time;
        ?>
        <?php echo $form->field($model, 'end_time')->widget(DateControl::className(), [
            'type' => DateControl::FORMAT_TIME,
        ]) ?>
    </div>
    <div class="col-xs-6">
        <?= $form->field($model, 'expire_days_cookie') ?>
    </div>

    <div class="clearfix"></div>
    <?php $this->endBlock('general'); ?>

    <?php $itemsTab[] = [
        'label' => Yii::t('cruds', 'general'),
        'content' => $this->blocks['general'],
    ];
    ?>

    <?= Tabs::widget(
        [
            'encodeLabels' => false,
            'items' => $itemsTab
        ]
    );
    ?>
    <?= CloseSaveButtonWidget::widget(['model' => $model]); ?>
    <?php ActiveForm::end(); ?>
</div>
