<?php

/**
 * Aria S.p.A.
 * OPEN 2.0
 *
 *
 * @package    amos\sitemanagement\views\site-management-container
 * @category   CategoryName
 */
use amos\sitemanagement\Module;
use open20\amos\core\forms\ActiveForm;
use open20\amos\core\forms\CloseSaveButtonWidget;
use open20\amos\core\forms\Tabs;
use open20\amos\core\helpers\Html;
use kartik\select2\Select2;

/**
 * @var yii\web\View $this
 * @var amos\sitemanagement\models\SiteManagementContainer $model
 * @var yii\widgets\ActiveForm $form
 */
$js                    = <<<JS
    if($('#is-masonry').is(':checked')){
            $('#num-columns').hide();
            $('#num-columns select').val('');
        }
        else {
            $('#num-columns').show();
        }
        
    $('#is-masonry').click(function(){
        if(this.checked){
            $('#num-columns').hide();
            $('#num-columns select').val('');
        }
        else {
            $('#num-columns').show();
        }
    });
JS;
$permissions           = \amos\sitemanagement\utility\SiteManagementUtility::getEnabledPermissionsForUpdate();
$module                = \Yii::$app->getModule('sitemanagement');
$enableFixedContainers = (!empty($module) && $module->enableFixedContainers) ? true : false;
$this->registerJs($js);
?>

<div class="site-management-container-form col-xs-12 nop">

    <?php $form                  = ActiveForm::begin(); ?>

    <?php $this->beginBlock('generale'); ?>

    <div class="col-lg-6 col-sm-6">
        <?=
// generated by schmunk42\giiant\generators\crud\providers\core\RelationProvider::activeField
        $form->field($model, 'section_id')->widget(Select2::className(),
            [
            'data' => \yii\helpers\ArrayHelper::map(\amos\sitemanagement\models\SiteManagementSection::getAvailableSections($model)->all(),
                'id', 'name'),
            'options' => ['placeholder' => Module::t('amossistemanagement', 'Select...')]
            ]
        );
        ?>
    </div>

    <div class="col-lg-6 col-sm-6">
        <?= $form->field($model, 'page_name')->textInput(['maxlength' => true]) ?>
    </div>
    <div class="col-lg-6 col-sm-6">
        <?=
        $form->field($model, 'element_random')->dropDownList(
            [0 => Module::t('amossitemanagement', 'No'), 1 => Module::t('amossitemanagement', 'Si')],
            [
            'prompt' => Module::t('amossitemanagement', 'Select'),
            ]
        );
        ?>
    </div>



    <?php if ($enableFixedContainers) { ?>
        <?php if (!$model->isNewRecord) { ?>
            <div style="display:none">
                <?= $form->field($model, 'fixed_template_id')->hiddenInput() ?>
            </div>
        <?php } else { ?>
            <div class="col-lg-6 col-sm-12">
                <?=
                $form->field($model, 'fixed_template_id')->widget(Select2::className(),
                    [
                    'data' => \yii\helpers\ArrayHelper::map(\amos\sitemanagement\models\base\SiteManagementTemplate::find()->all(),
                        'id', 'name'),
                    'options' => ['placeholder' => Module::t('amossistemanagement', 'Select...')]
                ])
                ?>
            <?php } ?>
        </div>
    <?php } ?>

    <?php if ($enableFixedContainers) { ?>
        <div hidden>
            <?= $form->field($model, 'element_limit')->hiddenInput(['value' => 1]) ?>
            <?= $form->field($model, 'is_masonry')->hiddenInput(['value' => 0]) ?>
            <?= $form->field($model, 'num_columns')->hiddenInput(['value' => 1]) ?>
        </div>
    <?php } else { ?>
        <div class="col-lg-6 col-sm-12">
            <?= $form->field($model, 'element_limit') ?>
        </div>

        <div class="col-lg-3 col-sm-12">
            <?= $form->field($model, 'is_masonry')->checkbox(['id' => 'is-masonry']) ?>
        </div>
        <div id="num-columns" class="col-lg-3 col-sm-12">
            <?=
            $form->field($model, 'num_columns')->widget(Select2::className(),
                [
                'data' => ['1' => '1', '2' => '2', '3' => '3', '4' => '4'],
                'options' => ['placeholder' => Module::t('amossistemanagement', 'Select...')],
                'pluginOptions' => [
                    'allowClear' => true
                ]
            ])
            ?>
        </div>
    <?php } ?>



    <div class="col-lg-12 col-sm-12">
        <?= $form->field($model, 'title')->textInput(['maxlength' => true]) ?>
    </div>

    <div class="col-lg-12 col-sm-12">
        <?= $form->field($model, 'description')->textarea(['rows' => 6]) ?>
    </div>

    <?php if (\Yii::$app->user->can('SITE_MANAGEMENT_ADMINISTRATOR') && !empty($permissions)) { ?>
        <div class="row">
            <div class="col-lg-12 col-sm-12">
                <?=
                $form->field($model, 'permission')->widget(Select2::className(),
                    [
                    'data' => \amos\sitemanagement\utility\SiteManagementUtility::getEnabledPermissionsForUpdateWithLabel(),
                    'options' => ['placeholder' => Module::t('amositemanagement', 'Seleziona...')]
                ])
                ?>
            </div>
        </div>
    <?php } ?>

    <div class="col-lg-12 col-sm-12"><h3><?= Module::t('amossitemanagement', 'Elements') ?></h3></div>
    <div class="col-lg-12 col-sm-12">
        <?php if (!$model->isNewRecord) { ?>
            <?=
            Html::a(\Yii::t('amossitemanagement', '#add_elements'),
                ['/sitemanagement/site-management-container-element-mm/create', 'idContainer' => $model->id],
                ['class' => 'btn btn-navigation-primary'])
            ?>

            <?php
            $max      = \amos\sitemanagement\models\SiteManagementContainerElementMm::find()->andWhere(['container_id' => $model->id])->max("site_management_container_element_mm.elem_order");
            $min      = \amos\sitemanagement\models\SiteManagementContainerElementMm::find()->andWhere(['container_id' => $model->id])->min("site_management_container_element_mm.elem_order");
            echo \open20\amos\core\views\AmosGridView::widget([
                'dataProvider' => $dataProviderElements,
                'columns' => [
                    [
                        'label' => 'Ordina',
                        'value' => function ($model) use ($max, $min) {
                            $buttons = '';
                            if ($model->elem_order != $min) {
                                $buttons .= Html::a(\open20\amos\core\icons\AmosIcons::show('long-arrow-up'),
                                        [
                                        '/sitemanagement/site-management-container-element-mm/order-container', 'id' => $model->id,
                                        'container_id' => $model->container_id, 'direction' => 'up'],
                                        ['class' => 'btn btn-tools-secondary']);
                            }
                            if ($model->elem_order != $max) {
                                $buttons .= Html::a(\open20\amos\core\icons\AmosIcons::show('long-arrow-down'),
                                        [
                                        '/sitemanagement/site-management-container-element-mm/order-container', 'id' => $model->id,
                                        'container_id' => $model->container_id, 'direction' => 'down'],
                                        ['class' => 'btn btn-tools-secondary']);
                            }
                            return $buttons;
                        },
                        'visible' => $model->is_masonry ? false : true,
                        'format' => 'raw'
                    ],
                    'element.siteManagementTemplate.name',
                    'element.title',
                    [
                        'attribute' => 'element.description',
                        'value' => function($model) {
                            return $model->element->getDescription(true);
                        }
                    ],
                    'siteManageContElemPubblication.siteManagePubblicationType.name',
                    [
                        'attribute' => 'siteManageContElemPubblication.start_date',
                        'value' => function($model) {
                            if (empty($model->siteManageContElemPubblication->start_date)) {
                                return Module::t('amossitemanagement', 'Always');
                            }
                            return \Yii::$app->formatter->asDatetime($model->siteManageContElemPubblication->start_date);
                        },
                    ],
                    [
                        'class' => \open20\amos\core\views\grid\ActionColumn::className(),
                        'controller' => 'site-management-container-element-mm',
                        'template' => '{updateElement}{update}{delete}',
                        'buttons' => [
                            'updateElement' => function($url, $model) {
                                return Html::a(\open20\amos\core\icons\AmosIcons::show('edit'),
                                        ['/sitemanagement/site-management-element/update', 'id' => $model->element_id],
                                        [
                                        'class' => 'btn btn-tools-secondary',
                                        'title' => Module::t('amossitemanagement', '#modify_element')
                                ]);
                            },
                            'update' => function($url, $model) {
                                return Html::a(\open20\amos\core\icons\AmosIcons::show('globe'), $url,
                                        [
                                        'class' => 'btn btn-tools-secondary',
                                        'title' => Module::t('amossitemanagement', '#modify_pubblication')
                                ]);
                            }
                        ]
                    ]
                ],
            ]);
        } else {
            ?>
            <div class="col-lg-12 col-sm-12">
            <?= Module::t('amossitemanagement', '#is_needed_saving_the_element'); ?>
            </div>
<?php } ?>
    </div>

    <div class="clearfix"></div>
    <?php $this->endBlock(); ?>

    <?php
    $itemsTab[] = [
        'label' => Module::t('amossitemanagement', 'generale'),
        'content' => $this->blocks['generale'],
    ];
    ?>

    <?=
    Tabs::widget(
        [
            'encodeLabels' => false,
            'items' => $itemsTab
        ]
    );
    ?>
<?= CloseSaveButtonWidget::widget(['model' => $model]); ?>
<?php ActiveForm::end(); ?>
</div>
